name: .NET Core Enterprise CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        # Включаем поддержку preview-версий и ставим 10-й .NET
        dotnet-version: '10.0.x'
        include-prerelease: true

    - name: Restore NuGet dependencies
      # Добавляем правильный двойной путь
      run: dotnet restore F1StrategySimulator/F1StrategySimulator/F1StrategySimulator.csproj

    - name: Compile solution (Release)
      # И здесь тоже удваиваем папку
      run: dotnet build F1StrategySimulator/F1StrategySimulator/F1StrategySimulator.csproj --configuration Release